# Clock bridge (Gazebo -> ROS)
- ros_topic_name: "/clock"
  gz_topic_name: "/world/ackermann_world/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: "GZ_TO_ROS"

# Cmd velocity bridge (ROS -> Gazebo)
- ros_topic_name: "/cmd_vel"
  gz_topic_name: "/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "gz.msgs.Twist"
  direction: "ROS_TO_GZ"

# Odometry bridge (Gazebo -> ROS)
- ros_topic_name: "/odom"
  gz_topic_name: "/odometry"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.Odometry"
  direction: "GZ_TO_ROS"

# Pose bridge (Gazebo -> ROS)
- ros_topic_name: "/pose"
  gz_topic_name: "/pose"
  ros_type_name: "geometry_msgs/msg/PoseStamped"
  gz_type_name: "gz.msgs.Pose"
  direction: "GZ_TO_ROS"

# TF Bridge (Crucial for Odometry to work in RViz)
- ros_topic_name: "/tf"
  gz_topic_name: "/tf"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: "GZ_TO_ROS"

# Joint states bridge (Gazebo -> ROS)
- ros_topic_name: "/joint_states"
  gz_topic_name: "/world/ackermann_world/model/ackermann_robot/joint_state"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: "GZ_TO_ROS"